### PR TITLE
feature/Casys

### PR DESCRIPTION
**Pull request by Sandy-CHERY**
## Description

Fixes 1 Change Cassys to solve the max stack size reached problem

## Motivation and Context

Alexis Neme have a problem :
"When I execute Cassys command (below) with IDE it generates the error "Max stack size reached" (attcahed file)
"Local\Unitex\App\UnitexToolLogger.exe" Cassys "-aUnitex3_2\English\Alphabet.txt" "-tUnitex3_2\English\Corpus\text.snt" "-lUnitex3_2\English\CasSys\cascade.csc" -v "-rUnitex3_2\English\Graphs" "--input_offsets=Unitex3_2\English\Corpus\text_snt\normalize.out.offsets" -qutf8-no-bom

When I execute Cassys command (below) with a command line, it does generate an error
"Local\Unitex\App\UnitexToolLogger.exe" Cassys "-aUnitex3_2\English\Alphabet.txt" "-tUnitex3_2\English\Corpus\text.snt" "-lUnitex3_2\English\CasSys\cascade.csc" -v "-rUnitex3_2\English\Graphs" "--input_offsets=Unitex3_2\English\Corpus\text_snt\normalize.out.offsets" -qutf8-no-bom --locate_argument=--stack_max=8000 --locate_argument=--max_matches_per_subgraph=800 --locate_argument=--max_matches_at_token_pos=8000

I propose to include these parameters in bold to the Cassys command line call from the IDE"

## What I did

In gramlab-ide\unitex\src\fr\umlv\unitex\process\commands\CommandBuilder.java,
when we create the Cassys comand "-qutf8-no-bom", I add "-qutf8-no-bom --locate_argument=--stack_max=8000 --locate_argument=--max_matches_per_subgraph=800 --locate_argument=--max_matches_at_token_pos=8000"

### CODE REVIEW

**Review by martinec — CHANGES_REQUESTED** [review]
As you can see [here](https://github.com/UnitexGramLab/gramlab-ide/pull/158/files), the PR attempts to remove 318 locs and then add 368:
Screenshot from 2021-09-24 16-50-52
It is not clear what part of the code is being modified. 
Can you do a PR pointing only the changes made? This is not only for code maintenance, but also for ease of review. Thanks !

**Comment by alexis-neme** [comment]
Hi Guys,

Please I am waiting for this fix,
it is almost one month since Sandy has made the fix *CASYS - MAX Stack
Reached in Java-IDE*
I do not know the problem exactly, but please do the necessary so that the
fix will be included in the next release ( and if possible this week).


Thanks, Sandy for your work
Thanks Cristian,
 Merci Beaucoup pour votre travail

**Comment by Sandy-CHERY** [comment]
Bonjour,
J'ai modifié les ligne118, 120 et 122.
Les autres lignes sont marqué comme modifié car j'ai remplacé le fichier "CommandBuilder.java" par le nouveau lors du pull request sur ma branche personnelle.

**Comment by Sandy-CHERY** [comment]
OK, I thing the problem is solve.

**Review by martinec — CHANGES_REQUESTED** [review]
The `locate_argument` options are being introduced as part of the `getOutputEncoding()` function. What is the motivation behind to make these changes here?

By way of example, a call to `getOutputEncoding()` for a `UTF16LE` encoding will be equal to : `--locate_argument=--stack_max=8000 --locate_argument=--max_matches_per_subgraph=800 --locate_argument=--max_matches_at_token_pos=8000\r\n`. This is not the expected value for a function named  `getOutputEncoding()` intended to generate the output encoding parameter. 

As further example,  calling `getOutputEncoding()` without encoding, will be equal to `null`

The edge effect of introducing the changes here will be that all calls to `getCommandLine()`, no matter which Unitex module is being used, will produce CasSys-specific parameters.

In any case, as now your PR is updated and the changes and motivation are clearer (thanks for that). I propose you to take a look to the  `[modulename]Command` classes [here](https://github.com/UnitexGramLab/gramlab-ide/tree/master/unitex/src/fr/umlv/unitex/process/commands).

First you will check the [`CassysCommand`](https://github.com/UnitexGramLab/gramlab-ide/blob/master/unitex/src/fr/umlv/unitex/process/commands/CassysCommand.java) class which extends  `CommandBuilder`. Then, you will need (at least):

- Implement the functions `maxMatchesPerSubgraph()` and `maxMatchesPerToken()` (tip: for an example, see [`LocateCommand`](https://github.com/UnitexGramLab/gramlab-ide/blob/master/unitex/src/fr/umlv/unitex/process/commands/LocateCommand.java))
- Use these new functions when instantiate a new `CassysCommand` from [`CassysFrame`](https://github.com/UnitexGramLab/gramlab-ide/blob/master/unitex/src/fr/umlv/unitex/frames/CassysFrame.java) 

>Off-topic:
Once these changes will be done, I will do not merge them directly with master, mainly because the values of stack_max (`8000`) and  max_matches_per_subgraph (`800`) will be hard-coded. Instead, using [`LocateFrame`](https://github.com/UnitexGramLab/gramlab-ide/blob/master/unitex/src/fr/umlv/unitex/frames/LocateFrame.java) as example, new UI elements need to be introduced to allow users to change the default values. But this is a different discussion, for the moment, as a first step, implementing the changes in `CassysCommand` is a must.

**Comment by alexis-neme** [comment]
Thanks for your work on this, For you all.

Is the feature (#158) included in the new built and where to download it?

Thanks again

Alexis

**Comment by martinec** [comment]
>  Is the feature (#158) included in the new built 

The Pull Requests carrying new features or bug fixes are only included in the main code once tested and approved, changes were requested on PR #158 because it breaks the application.

> and where to download it? 

Once ready, you will be able to download Unitex/GramLab 4.0-alpha directly from https://unitexgramlab.org.

**Comment by alexis-neme** [comment]
Bonjour Sandy
(cc Denis, Cristian)

In fact,* .jar *is working good and it is easier for me to test.
(FYI:  your  *.jar* is with JRE 1.8.0,  I needed to update JRE  on my
windows 10.)

Merci a vous tous,
Alexis


PS: Maybe you know this,
I think it will be better if you read the parameters from the interface
and call *Cassys *with all  these parameters (if possible) specified in the
interface

[image: image.png]

**Comment by martinec** [comment]
> In fact,* .jar *is working good and it is easier for me to test.

For the sake of clarity current changes broke the application, as you're only using CaSys this is not a noticeable problem.

Indeed, if you go `Info > Console` you will notice that other commands than `Cassys`, like `Grf2Fst2`, are been calling using "--locate_argument=...," :

```
UnitexToolLogger Grf2Fst2 "/home/Unitex-GramLab-4.0-alpha/French/Dela/Dnum-ord.grf" -y -qutf8-no-bom --locate_argument=--stack_max=8000 --locate_argument=--max_matches_per_subgraph=800 --locate_argument=--max_matches_at_token_pos=8000
```

Running this command line in a shell console gives the following results :

```
Invalid option --locate_argument=--stack_max=8000
```

This is evident because the proposed changes are wrongly spreading `--locate_argument` for each `getOutputEncoding()` call.

**Comment by alexis-neme** [comment]
I see,

Thanks Cristian for your notes and follow-ups

Alexis

**Comment by Sandy-CHERY** [comment]
Bonjour,

J'ai modifié les méthodes statiques dans la classe abstraite.

**Pull request closed without merging**
