### PR TITLE
Add copy button to error message dialogs Issue #17

### PR DESCRIPTION
**Pull request by aleksandrachasch**
Button "Copy error message" that copies text of the error message into system clipboard. The button has been added to "Java Exception" error dialog (as shown in #10), and ProcessInfo dialog. Issue #17

### CODE REVIEW

**Comment by Mukarr** [comment]
@aleksandrachasch I built your commit and tried to test it.
In the ProcessInfo Dialog, after clicking the copy error message button, contents of my clipboard were `fr.umlv.unitex.console.Couple@4652c8b5` and the screenshot is
screenshot from 2016-05-12 02 18 33

**Comment by Mukarr** [comment]
Approved !! The copy button now works fine in case of an error.

**Comment by martinec** [comment]
When testing on Linux, copy multiple times retains old clipboard data. Can you guys confirm this please?

**Comment by Mukarr** [comment]
Yes. That's true for linux atleast.

**Comment by Mukarr** [comment]
Yes, if by retain old data you mean that each time you click 'Copy error message', the error contents are copied to clipboard again. 
Clicking thrice on the button, stores the same message thrice in clipboard as can be seen below.
screenshot from 2016-05-14 01 46 32

**Comment by aleksandrachasch** [comment]
Dear @martinec and @Mukarr, could you please have a look at new changes. Now, if a copybutton on ProcessInfoFrame dialog is pressed more than one time, the warning message `"The error message has already been copied to clipboard"` appears. The content of the clipboard remains the same.

**Comment by martinec** [comment]
> Yes, if by retain old data you mean that each time you click 'Copy error message', the error contents are copied to clipboard again.

No,

**What steps will reproduce the problem?**

1. Launch Unitex.jar
1. Select French as working language
1. Text > Open > 81jours.txt
1. Do you want to process the text ? Answer **No**
1. Text > Locate Pattern
1. Locate configuration > Locate pattern in the form of > Regular expression
1. Put ``*`` on the text field
1. Click Copy error message
1. Click Copy error message

**What is the expected output?**

``Syntax error in regular expression``

**What do you see instead?**

``Syntax error in regular expression\nSyntax error in regular expression``

**Comment by martinec** [comment]
> Now, if a copybutton on ProcessInfoFrame dialog is pressed more than one time, the warning message "The error message has already been copied to clipboard" appears. **The content of the clipboard remains the same**.

This is not necessarily true since, after the first click to 'Copy error message', the contents of the clipboard can be changed or cleared by any other application.

**Comment by aleksandrachasch** [comment]
@martinec, 

> No,

> What steps will reproduce the problem?

   > Launch Unitex.jar
    Select French as working language
    Text > Open > 81jours.txt
    Do you want to process the text ? Answer No
    Text > Locate Pattern
    Locate configuration > Locate pattern in the form of > Regular expression
    Put * on the text field
    Click Copy error message
    Click Copy error message

>What is the expected output?

>Syntax error in regular expression

>What do you see instead?

>Syntax error in regular expression\nSyntax error in regular expression

Does the problem still remain after the last [commit](https://github.com/UnitexGramLab/gramlab-ide/pull/20/commits/77faadbd1c2538b5bf3861310ca61bdc5d4efafd)?

**Comment by martinec** [comment]
> Does the problem still remain after the last commit?

The problem still remains on 77faadb. Let's take a look at the next scenario:

1. Launch Unitex.jar
1. Select French as working language
1. Text > Open > 81jours.txt
1. Do you want to process the text ? Answer No
1. Text > Locate Pattern
1. Locate configuration > Locate pattern in the form of > Regular expression
1. Put * on the text field
1. Click Copy error message. **Clipboard content**:  ``Syntax error in regular expression``
1. Click Copy error message. **Clipboard content**:  ``Syntax error in regular expression``
1. Click OK
1. Text > Locate Pattern
1. Locate configuration > Locate pattern in the form of > Regular expression
1. Put * on the text field
1. Click Copy error message. **Clipboard content**:  ``Syntax error in regular expression\nSyntax error in regular expression``

Moreover, regarding the implemented approach to prevent to copy twice (e.g after 8.), take in account, as indicated in my [previous comment](#issuecomment-219215325),that the contents of the clipboard can be changed or cleared by any other application. Thus, nothing guarantees that the error message can be copied again if required.

**Comment by martinec** [comment]
LGTM. Thank you!

**Pull request merged**
