### PR TITLE
ReUp #130 [fix] Resolve LeXimir editor issues

### PR DESCRIPTION
**Pull request by FLambertD**
## Description
- This is an update of the PR130 "[fix] Resolve LeXimir editor issues" with changes discussed by the review.

- General:
. The path of the dictionaries in the DELAS edition is now readable (it only shows the name of the file now instead of the absolute path which was not readable)
. The folder that contains the dictionary that is opened with the editor is registered and if the name of some entries are changed in the editor, the file is saved in the same folder (working directory).
. Some fixes about actions that were possible (but that don't have a sense) like trying to open a non existent file or not selecting any files.

- The save:
. is now made in the right folder
. now saves the file with the encoding selected by the user in Preferences/Encoding

- The statistics:
. now have a default path that is suggested by the user
. now have a folder dedicated to them in Dela/Delas/Statistics
. now saves in the file with the right encoding (from the preferences)

- Check Duplicates:
. the research of duplicates on a filtered table now works correctly
. the duplicates table is more readable

- Filtering fields in the editor:
. "Inverted Lemma" now works with "Exact Match"
. The filter on "FST code" works now as it should (like a "Start with" filter)
. The regex are now recognized with "[" and "]"

## Motivation and Context
Most of these problems were causing the DELAS editor to not be logical in some way it worked.
The idea of this editor is to be an integrated version of LeXimir so I had it tested by Cvetana Krstev and I made the changes that was suggested by her.

## How Has This Been Tested?
The changes I made were tested on my environment (Linux) ,on my Windows, and by Cvetana Krstev (Windows). All bug fixes tested on different environment and with a lot of different situations.

## Type of files
- [ ] `bin`: Binary files
- [ ] `ci`: Continuous integration files
- [ ] `doc`: Documentation files
- [x] Plain-text source code files

## Level of change

- [ ] `break`: Breaking change
- [ ] `exp`: Experimental change
- [ ] `tmp`: Temporal change
- [ ] `major`: Major change
- [ ] `minor`: Minor change
- [ ] `sec`: Vulnerability-related change
- [x] None of the above (normal change)

## Type of change

- [ ] `deprecat`: Deprecation of a once-stable feature
- [ ] `enhance`: Enhancement in existing functionality
- [x] `fix`: Bug fix
- [ ] `feature`: New feature
- [ ] `hotfix`: Hotfix for bugs
- [ ] `refactor`: Improve coding style, comments
- [ ] `remove`: Remove a feature

## Checklist:
- [x] My code compiles
- [x] My code follows the code style of this project
- [x] My code includes javadoc/doxygen where appropriate
- [x] My code is well factored, so that there is not repetitive code in the wild
- [ ] My code does not require a change in the documentation, if so I already opened an issue to list the changes
- [x] I have read the **CONTRIBUTING** document
- [x] I have read the **Commit Message Guidelines**
- [x] I understand that all commits on my pull request will be squashed to a single good one

### CODE REVIEW

**Comment by martinec** [comment]
Hello! Looks like this PR is equal to #130 plus 3 minor commits. Is there a reason to have created a new PR and not to have updated the original one? One of the issues of doing this is that I no longer have visibility over the past review process.

**Comment by martinec** [comment]
Attention! This PR should not be done against master, it must be done against UnitexGramLab:feature/90

**Comment by eric-laporte** [comment]
> Hello! Looks like this PR is equal to #130 plus 3 minor commits. Is there a reason to have created a new PR and not to have updated the original one? One of the issues of doing this is that I no longer have visibility over the past review process.

The interns and I hesitated about the two solutions. Updating the original PRs would have been our best choice, except for the fact that apparently the original authors of the PRs would have had to give the interns the rights to do so, and we weren't sure about their time of reaction.

**Comment by eric-laporte** [comment]
> 
> 
> Attention! This PR should not be done against master, it must be done against UnitexGramLab:feature/90

What do you mean concretely? When I click on "Add my review" or "Review changes", GitHub does not ask against what.

**Comment by martinec** [comment]
> > Attention! This PR should not be done against master, it must be done against UnitexGramLab:feature/90
> 
> What do you mean concretely? When I click on "Add my review" or "Review changes", GitHub does not ask against what.

See #149 against [master](https://github.com/UnitexGramLab/gramlab-ide/tree/master) :

g01

Versus #130 against [feature/90](https://github.com/UnitexGramLab/gramlab-ide/tree/feature/90):

g02

**Comment by martinec** [comment]
I'm closing this PR because it's supposed to be against feature/90

**Pull request closed without merging**
