### PR TITLE
[feature] Add option to flatten graph when using `explore grapth paths`

### PR DESCRIPTION
**Pull request by Kalkhas**
Add option to flatten the graph before exploring it.
See #115.

## Description
Add a checkbox to flatten the graph.
Add a button to show the options available for flattening.
Allow Flatten Frame to be used outside from Compile & Flatten.

## Motivation and Context
It is not currently possible to flatten graphs before exploring them as they are recompiled (without flattening) every time we explore them.

## How Has This Been Tested?
This has been tested on various graphs available in Unitex/GramLab.

## Screenshots (if appropriate):

flatten-explore

## Type of files

- [ ] `bin`: Binary files
- [ ] `ci`: Continuous integration files
- [ ] `doc`: Documentation files
- [x] Plain-text source code files

## Level of change

- [ ] `break`: Breaking change
- [ ] `exp`: Experimental change
- [ ] `tmp`: Temporal change
- [ ] `major`: Major change
- [ ] `minor`: Minor change
- [ ] `sec`: Vulnerability-related change
- [x] None of the above (normal change)

## Type of change

- [ ] `deprecat`: Deprecation of a once-stable feature
- [ ] `enhance`: Enhancement in existing functionality
- [ ] `fix`: Bug fix
- [x] `feature`: New feature
- [ ] `hotfix`: Hotfix for bugs
- [ ] `refactor`: Improve coding style, comments
- [ ] `remove`: Remove a feature

## Checklist:

- [x] My code compiles
- [x] My code follows the code style of this project
- [x] My code includes javadoc/doxygen where appropriate
- [x] My code is well factored, so that there is not repetitive code in the wild
- [x] My code does not require a change in the documentation, if so I already opened an issue to list the changes
- [x] I have read the **CONTRIBUTING** document
- [x] I have read the **Commit Message Guidelines**
- [x] I understand that all commits on my pull request will be squashed to a single good one

### CODE REVIEW

**Comment by Kalkhas** [comment]
Looks better now

flatten_graph_checkbox

**Comment by martinec** [comment]
> Looks better now
> 
> flatten_graph_checkbox

@Kalkhas, @eric-laporte, the current UI seems kind of messy because there's so much floating stuff.   to put a little bit of order would be the best :

explore

What do you  think about ? 

Mockup is editable on https://unitexgramlab.mybalsamiq.com

**Comment by Kalkhas** [comment]
That's definitely a big improvement but I feel like this should be part of a different pull request.
I won't have time right now to tackle this.

**Comment by martinec** [comment]
For the UI improvement check #122

**Comment by martinec** [comment]
> Looks better now
> 
> flatten_graph_checkbox

It would be less clutter if the button `Flattening options`  is aligned with the text area (`100`) above it. Please do it.

**Comment by Kalkhas** [comment]
Here you go

button_alignment

**Comment by martinec** [comment]
LGTM, I hope that #122 can be done soon.

**Pull request merged**
